###
GET http://localhost:8080/
###
GET http://localhost:8080/home
###
GET http://localhost:8080/admin
###
GET http://localhost:8080/admin/test1
###
GET http://localhost:8080/registered
###
GET http://localhost:8080/registered/test1
###
GET http://localhost:8080/registered/test2
###
GET http://localhost:8080/user
###
GET http://localhost:8080/user/test1
###
GET http://localhost:8080/user/test2
###
GET http://localhost:8080/bar
###
GET http://localhost:8080/foo
###
GET http://localhost:8080/bar/test/master
###
GET http://localhost:8080/foo/master
###
GET http://localhost:8080/anonymous/test1
###
GET http://localhost:8080/anonymous/foo/test2
###
